### PR TITLE
Remove search box from front page

### PR DESCRIPTION
**Pull request by stefanv**
To address #37 (will add another PR to correctly place search box in docs rendering)

### CODE REVIEW

**Comment by jni** [comment]
Sorry what's the logic here?

**Comment by soupault** [comment]
Superseded by https://github.com/scikit-image/scikit-image/pull/2287.

**Comment by soupault** [comment]
What am I even talking about...

**Comment by stefanv** [comment]
The idea is to remove the documentation search box from the front page, and to make it prominently visible on the documentation page instead.

**Comment by ahojnnes** [comment]
@stefanv -1 on this, I use the search box very frequently on the front page when searching for things...

**Comment by soupault** [comment]
@stefanv I think the searchbox is a nice feature to show on all possible pages.

**Comment by ahojnnes** [comment]
How about removing the "Guidelines" and extending the page with additional information about who the community is (e.g., links to mailing list, contributors page, etc.)? Then, the search box fit on the same line again...

**Comment by stefanv** [comment]
You use it because it is there; but if it weren't, would it be much
harder to navigate to the docs page and bookmark that instead?

**Comment by ahojnnes** [comment]
@stefanv lol, yes, I use it because it is there, and I think, it is useful... :-)

**Comment by stefanv** [comment]
Yes, but the question remains: is it much more useful than only having it on the docs page?

Front page estate is valuable, so we need to think carefully what we put there.

**Comment by ahojnnes** [comment]
I can only repeat myself, that I think it is valuable to me. But if I am the only one, I am happy to make a sacrifice :-)

**Comment by stefanv** [comment]
Another option is to tweak the width of the main page by a few pixels to
allow the bar to fit in :)

But that's a bit more work, so if someone else wants to take that
I'd be happy.

**Comment by jni** [comment]
@stefanv I'm with @ahojnnes, I think the search bar should stay on the home page. There's a reason Google succeeded over Yahoo: typing what you're looking for is almost always faster than navigating a hierarchical listing.

**Comment by stefanv** [comment]
The discussion wasn't about complete removal, but rather having it 
prominently display on the docs page. Are you saying that you want it to be 
on the front page specifically?

**Comment by jni** [comment]
@stefanv I would say it's good for the search bar to appear in the home page. Saving clicks is good.

**Comment by stefanv** [comment]
Saving clicks is good? So should we add a link to contributor guidelines, 
user guide, etc.?

I don't find blanket statements like that helpful in design decisions.

**Comment by ahojnnes** [comment]
@stefanv I have not heard a single argument from your side as to why to remove the search box is a good thing, other than the fact that the new community guideline link doesn't fit any more. I proposed a possible solution further above, which was silently ignored. Similar to @jni, I find the search box convenient and use it whenever I search for scikit-image API documentation.

**Comment by stefanv** [comment]
The argument is to de-clutter the main page, and to place emphasis on important links.

The documentation search functionality is confusing because it is not placed in the context of a docs page.  So, what version will it search?  What exactly will be searched?  In the docs page, we can make all this clear.

I heard that you find it convenient, but I am hard pressed to believe that it is much more convenient than having the box on the docs page.

As to your suggestion, that's a workaround for now, but it doesn't address the issue of the cluttered front page.  I am trying to get a better feeling why that specific element in that specific position is important to you guys, and once I do I can think in more detail about your other proposal.

**Comment by jni** [comment]
@stefanv ok, a more precise statement: imho, the search box should have close to the highest priority when it comes to being presented in the home page.

I wonder if @emmanuelle's website statistics can tell us here how often people use the search box rather than clicking on the other links.

Regarding your last comment, it appears that the box searches both the documentation and the gallery... I'm not clear to me what is and isn't searched for using that box, but perhaps what we should put is a "search this site" Google box there that covered all of scikit-image.org.

**Comment by stefanv** [comment]
I'd be happy with a search this site Google box.  But would that satisfy @ahojnnes?  Here's a sample search for regionprops: https://www.google.co.uk/?gfe_rd=cr&ei=cH3OV4DnC7PA8geHsKWAAQ&gws_rd=ssl#q=site:scikit-image.org+regionprops

**Comment by ahojnnes** [comment]
I find the Google search pretty useless, to be honest. Tried a few
different terms.

**Comment by jni** [comment]
@ahojnnes hmm, interesting, do you mean because it's not version-aware?

**Comment by ahojnnes** [comment]
That is one reason, but it also doesn't lead to the appropriate page right away. E.g., if I follow @stefanv's example, typing "regionprops" into our search bar immediately gives me the correct result and the link is an anchor to the right location on the `skimage.measure` page.

**Comment by ahojnnes** [comment]
@stefanv How about just making the search box less wide. The "Search documentation..." will still fit?

**Comment by stefanv** [comment]
That's the most pragmatic solution for now, I think :)

**Pull request closed without merging**
