### PR TITLE
Fix wording.

### PR DESCRIPTION
**Pull request by mkcor**
I guess 'welcoming' was the intended word.

I noticed this typo while navigating the website, in the context of https://github.com/scikit-image/scikit-image/issues/4988.

### CODE REVIEW

**Comment by mkcor** [comment]
f8d6afa comes from https://github.com/scikit-image/scikit-image/pull/4990

**Comment by emmanuelle** [comment]
thanks @mkcor! @stefanv is the CI failure due to the fact that Marianne's branch is on her fork and therefore the repo token is not used? I was not sure.

**Comment by mkcor** [comment]
> thanks @mkcor! @stefanv is the CI failure due to the fact that Marianne's branch is on her fork and therefore the repo token is not used? I was not sure.

#74 passed CI so it looks like this might be it.

**Comment by jni** [comment]
Looks like this was superseded by #74. Reopen if I'm mistaken. 😊

**Pull request closed without merging**
