### PR TITLE
Update copy_trees and gh-pages for python 3

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by JDWarner** [comment]
Does there need to be an explicit `from __future__ import print_function` in `gh-pages.py` for backwards compatibility, now that all `print` statements are instead `print()` functions?

**Comment by stefanv** [comment]
Yes, for when you run it under Python 2.

**Comment by JDWarner** [comment]
I'm happy to merge this once that compatibility import gets added to gh_pages.py

If you're busy I can merge this and fix the import myself in a separate PR.

**Comment by stefanv** [comment]
Ah, sorry, got your comment via email and thought you enquired as to why the line was there--but actually it is *missing*.  Let me fix.

**Comment by stefanv** [comment]
Done.

**Comment by JDWarner** [comment]
Thanks!

**Pull request merged**
