### PR TITLE
Add link to image.sc forum skimage questions

### PR DESCRIPTION
**Pull request by jni**

### CODE REVIEW

**Comment by stefanv** [comment]
Help forum feels like too generic a description, although I don't have a better phrase to suggest. But isn't the mailing list also a help forum?

**Comment by jni** [comment]
Image.sc forum? The problem with that is that it is confusing if you don't already know what it is.

By and large, the mailing list has become a place for public discussion of proposals, mostly by core members or frequent contributors to the library.

**Comment by stefanv** [comment]
Sure, but what then is the difference between Help Forum and StackOverflow?

**Comment by jni** [comment]
SO is for programmers/programming questions. Generally if you post a question like "how do I pick out the blue M&M's", with no code, people are going to be hostile. Not us, but many other SO contributors. The Help Forum, if you have a look at it, is, at least currently, used for more general questions of this kind.

In short, the Help Forum is our "candidates for future gallery examples" forum. ;)

**Comment by stefanv** [comment]
The question is how to encode this in the namings.

**Comment by jni** [comment]
It's a hard question. An initial proposal:

- Analysis help
- Programming help
- Bug reports
- Discuss new ideas
- How to contribute

I'd remove the link to Travis, that's a bit gratuitous in this location, actually.

**Comment by ctrueden** [comment]
@stefanv @jni What do you think about this?

scikit-image-sidebar

Here is the patch for it:

https://github.com/scikit-image/scikit-image-web/compare/image-forum...ctrueden:imagej-forum-ctr

The only subtitle I don't love is "dev. Q+A" for StackOverflow, but it's tricky to come up with a phrase short enough to fit floating right on the same line. And maybe it's fine. What do you think?

**Comment by stefanv** [comment]
Thanks, Curtis.  This looks good, but I agree that "dev. Q+A" is not very representative.  Perhaps leave it blank, or "coding Q&A".

**Comment by jni** [comment]
How about "coding help", or "code help" if the former is too long? But anyway I like the list very much, thanks @ctrueden! @stefanv if you agree with either of my suggestions I'll create a PR from @ctrueden's commit and push that minor change to it.

**Comment by stefanv** [comment]
Sure, that's fine with me.

**Comment by stefanv** [comment]
@jni Should we also add a link to the zulip chat room? Either way, please proceed and merge!

**Comment by jni** [comment]
@stefanv perhaps we should, another time. I imagine it would replace the zulip "Open chat" box?

**Comment by jni** [comment]
@ctrueden it's finally live!!! :grinning: thanks for your patience! =)

**Pull request merged**
